### ISSUE TITLE
Replace wayland-session.target with ConditionEnvironment=wayland

### ISSUE THREAD

**Issue by markstos** [xdbob/sway-services#16]
It was proposed that systemd provide a standardized "wayland-session.target".

https://github.com/systemd/systemd/pull/15180

Instead, the approach implemented was a more general solution of adding `ConditionEnvironment=` to test environment variables. This was released in systemd v246 which in use now on at least Arch Linux. 

Given that, we could adopt the the approach by no longer shipping or referencing a `wayland-session.target`. 

Instead, rely on the standardized `graphical-session.target` and use `ConditionEnvironment=WAYLAND_DISPLAY` for services that should only launch under Wayland.

This approach would avoid conflicts with other projects that might otherwise ship a "wayland-session.target" for the same reason this project did.

**Comment by markstos** [comment]
Systems v247  is out now, which includes fixed support for ConditionEnvironment=

**Comment by WhyNotHugo** [comment]
Using `ConditionEnvironment=WAYLAND_DISPLAY` doesn't really work for this scenario due to https://github.com/systemd/systemd/issues/20366

The TLDR version is: if the service tries to start _before_ wayland, it's marked as not-startable and system won't retry after wayland has started -- even if the service is required by something else (e.g.: gets D-Bus activated).

**Comment by markstos** [comment]
@WhyNotHugo is right. Closing.
